# Novas perguntas do CEO (Aula 04)

In [1]:
import pandas as pd

data = pd.read_csv('datasets/kc_house_data.csv')

In [2]:
#1. Qual a média do preço de compra dos imóveis por "Nível"?
##        - Nível 0 -> Preço entre R$ 0  e R$ 321.950
##        - Nível 1 -> Preço entre R$ 321.950 e R$ 450.000
##        - Nível 2 -> Preço entre R$ 450.000 e R$ 645.000
##        - Nível 3 -> Acima de R$ 645.000


data['level'] = 'NA'

for i in range ( len( data )):
    
    if (data.loc[i, 'price']>0) & (data.loc[i, 'price'] < 321950):
        data.loc[i, 'level'] = '0'
        
    elif (data.loc[i, 'price']>321950) & (data.loc[i, 'price'] < 450000):
        data.loc[i, 'level'] = '1'
        
    elif (data.loc[i, 'price']>450000) & (data.loc[i, 'price'] < 645000):
        data.loc[i, 'level'] = '2'
    
    else:
        data.loc[i, 'price'] = '3'

In [3]:
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,level
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,1180,0,1955,0,98178,47.5112,-122.257,1340,5650,0
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639,2
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,770,0,1933,0,98028,47.7379,-122.233,2720,8062,0
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,1050,910,1965,0,98136,47.5208,-122.393,1360,5000,2
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,1680,0,1987,0,98074,47.6168,-122.045,1800,7503,2

In [4]:
#2. Qual a média do tamanho da sala de estar dos imóveis por "Size"?
##        - Size 0 -> Tamanho entre 0 e 1427 sqft
##        - Size 1 -> Tamanho entre 1427 e 1910 sqft
##        - Size 2 -> Tamanho entre 1910 e 2550 sqft
##        - Size 3 -> Acima de 2550 sqft


data['size'] = 'NA'

for i in range (len(data)):
    if (data.loc[i, 'sqft_living'] > 0) & (data.loc[i, 'sqft_living'] < 1427):
        data.loc[i, 'size'] = '0'
        
    elif (data.loc[i, 'sqft_living'] > 1427) & (data.loc[i, 'sqft_living'] < 1910):
        data.loc[i, 'size'] = '1'
        
    elif (data.loc[i, 'sqft_living'] > 1910) & (data.loc[i, 'sqft_living'] < 2550):
        data.loc[i, 'size'] = '2'
        
    else:
        data.loc[i, 'size'] = '3'

In [5]:
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,level,size
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,0,1955,0,98178,47.5112,-122.257,1340,5650,0,0
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,400,1951,1991,98125,47.7210,-122.319,1690,7639,2,3
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,0,1933,0,98028,47.7379,-122.233,2720,8062,0,0
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,910,1965,0,98136,47.5208,-122.393,1360,5000,2,2
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,0,1987,0,98074,47.6168,-122.045,1800,7503,2,1

In [11]:
#3. Adicione as seguintes informações ao conjunto de dados original:
##        - Place ID: Identificação da localização
##        - OSM Type: Open Street Map Type
##        - Country: Nome do País
##        - Country Code: Código do País

from geopy.geocoders import Nominatim

In [12]:
data['place_id'] = 'NA'
data['osm_type'] = 'NA'
data['country'] = 'NA'
data['country_code'] = 'NA'

geolocator = Nominatim (user_agent='geoapiExcercises')


for i in range ( len(data)):
    
    print('Loop:{}/{}'.format(i,len(data)))
    
    #Make query
    query = str( data.loc[i, 'lat'] ) + ',' + str( data.loc[i, 'long'] )
    
    #API request
    
    response = geolocator.reverse( query )
    
    #populate data
    if 'place_id' in response.raw:
        data.loc[i, 'place_id'] = response.raw['place_id']
        
    if 'osm_type' in response.raw:
        data.loc[i, 'osm_type'] = response.raw['osm_type']
        
    if 'country' in response.raw['address']:
        data.loc[i, 'country'] = response.raw['address']['country']
    
    if 'country_code' in response.raw['address']:
        data.loc[i, 'country_code'] = response.raw['address']['country_code']

Loop:0/21613
Loop:1/21613
Loop:2/21613
Loop:3/21613
Loop:4/21613
Loop:5/21613
Loop:6/21613
Loop:7/21613
Loop:8/21613
Loop:9/21613
Loop:10/21613
Loop:11/21613
Loop:12/21613
Loop:13/21613
Loop:14/21613
Loop:15/21613
Loop:16/21613
Loop:17/21613
Loop:18/21613
Loop:19/21613
Loop:20/21613
Loop:21/21613
Loop:22/21613
Loop:23/21613
Loop:24/21613
Loop:25/21613
Loop:26/21613
Loop:27/21613
Loop:28/21613
Loop:29/21613
Loop:30/21613
Loop:31/21613
Loop:32/21613
Loop:33/21613
Loop:34/21613
Loop:35/21613
Loop:36/21613
Loop:37/21613
Loop:38/21613
Loop:39/21613
Loop:40/21613
Loop:41/21613
Loop:42/21613
Loop:43/21613
Loop:44/21613
Loop:45/21613
Loop:46/21613
Loop:47/21613
Loop:48/21613
Loop:49/21613
Loop:50/21613
Loop:51/21613
Loop:52/21613
Loop:53/21613
Loop:54/21613
Loop:55/21613
Loop:56/21613
Loop:57/21613
Loop:58/21613
Loop:59/21613
Loop:60/21613
Loop:61/21613
Loop:62/21613
Loop:63/21613
Loop:64/21613
Loop:65/21613
Loop:66/21613
Loop:67/21613
Loop:68/21613
Loop:69/21613
Loop:70/21613
Loop:71/21613
Loop:72/21613
Loop:73/21613
Loop:74/21613
Loop:75/21613
Loop:76/21613
Loop:77/21613
Loop:78/21613
Loop:79/21613
Loop:80/21613
Loop:81/21613
Loop:82/21613
Loop:83/21613
Loop:84/21613
Loop:85/21613
Loop:86/21613

GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=47.2909&lon=-122.189&format=json&addressdetails=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

In [10]:
data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,lat,long,sqft_living15,sqft_lot15,level,size,place_id,osm_type,country,country_code
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,47.5112,-122.257,1340,5650,0,0,NA,NA,NA,NA
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,47.7210,-122.319,1690,7639,2,3,NA,NA,NA,NA
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,47.7379,-122.233,2720,8062,0,0,NA,NA,NA,NA
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,47.5208,-122.393,1360,5000,2,2,NA,NA,NA,NA
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,47.6168,-122.045,1800,7503,2,1,NA,NA,NA,NA

In [13]:
#4. Adicione os seguintes filtros no Mapa:
##        - Tamanho mínimo da área da sala de estar
##        - Número mínimo de banheiros
##        - Valor Máximo do Preço
##        - Tamanho máximo da área do porão
##        - Filtro das Condições do Imóvel
##        - Filtro por Ano de Construção

import plotly.express as px
import ipywidgets as widgets
from ipywidgets import fixed

In [14]:
data = pd.read_csv('datasets/kc_house_data.csv')

houses = data[['id', 'price', 'lat', 'long']].copy()

#define level
for i in range ( len(data)):
    if houses.loc[i, 'price'] <= 321950:
        houses.loc[i, 'level'] = 0
        
    elif (houses.loc[i, 'price'] > 321950) & (houses.loc[i, 'price'] <= 450000):
        houses.loc[i, 'level'] = 1
        
    elif (houses.loc[i, 'price'] > 450000) & (houses.loc[i, 'price'] <= 645000):
        houses.loc[i, 'level'] = 2
        
    else:
        houses.loc[i, 'level'] = 3
        
houses['level'] = houses['level'].astype (int)

In [68]:
data['house_condition'] = data['condition'].apply (lambda x: 'bad' if x <= 2 else 'regular'
                                                  if (x >= 3) & (x <= 4) else 'good')

data['min_living'] = data['sqft_living'].apply( lambda x: 0 if x < 1427 else
                                           1 if (x > 1427) & (x < 1910) else
                                           2 if (x > 1910) & (x < 2550) else 3)

data['level'] = data['price'].apply( lambda x: 0 if x < 321950 else
                                           1 if (x > 321950) & (x < 450000) else
                                           2 if (x > 450000) & (x < 645000) else 3)


style = {'description_width': 'initial'}

#Interactive buttons
living_limit = widgets.IntSlider(
    value= 6570,
    min = 290,
    max = 13540,
    step = 1,
    description='Minimum Sqft Living',
    disable=False,
    style = style)

condition_bar = widgets.Dropdown(
    options= data['house_condition'].unique().tolist(),
    value='regular',
    description='House Condition',
    disable=False)

price_limit = widgets.IntSlider(
    value= 540000,
    min = 75000,
    max = 7700000,
    step = 1,
    description='Maximum Price',
    disable=False,
    style = style)

min_bathroom = widgets.IntSlider(
    value = 4,
    min = 0,
    max = 8,
    step = 1,
    description='Minimum Bathrooms',
    disable=False,
    style = style)

max_basement = widgets.IntSlider (
    value = 2410,
    min = 0,
    max = 4820,
    step = 1,
    description='Maximum Sqft Basement',
    disable=False,
    style = style)

by_yr_built = widgets.IntSlider(
    value = 1955,
    min = 1900,
    max = 2015,
    step = 1,
    description='Year of Built',
    disable=False,
    style = style)

def update_map (data, condition, sqft_living, limit):
    houses = data [(data['price'] <= limit) &
                 (data['house_condition'] == condition) &
                 (data['min_living'] == sqft_living)] [['id', 'lat', 'long', 'price', 'level']]
    
    fig = px.scatter_mapbox (houses,
                            lat='lat',
                            lon='long',
                            color='level',
                            size='price',
                            color_continuous_scale=px.colors.cyclical.Edge,
                            size_max=15,
                            zoom=10)

    fig.update_layout( mapbox_style='open-street-map')
    fig.update_layout( height=600, margin={'r':0, 't':0,'l':0, 'b':0})
    fig.show()

In [67]:
widgets.interactive (update_map, data=fixed (data), condition=condition_bar, limit=price_limit, sqft_living=living_limit)

interactive(children=(Dropdown(description='House Condition', options=('regular', 'good', 'bad'), value='regul…

In [ ]:
#5. Adicione os seguintes filtros no Dashboard:
###        - Filtro por data disponível para compra
###        - Filtro por ano de renovação
###        - Filtro se possui vista para água ou não

In [70]:
import ipywidgets as widgets
from matplotlib import gridspec
from matplotlib import pyplot as plt

data = pd.read_csv ('datasets/kc_house_data.csv')

In [76]:
#data['year']=pd.to_datetime(data['date']).dt.strftime('%Y')
#data['year_week']=pd.to_datetime(data['date']).dt.strftime('%Y-%U')

#data de compra
data['date']=pd.to_datetime(data['date']).dt.strftime('%Y-%m-%d')

#data de renovacao
data['year_renew']=pd.to_datetime(data['yr_renovated']).dt.strftime('%Y')

#vista mar sim ou nao
data['is_waterfront']=data['waterfront'].apply(lambda x:'yes' if x==1 else 'no')

#https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html(ver outros botoes)

date_limit=widgets.SelectionSlider(
    options=data['date'].sort_values().unique().tolist(),
    value='2014-12-01',
    description='Disponivel para compra',
    continuosus_update=False,
    orientation='horizontal',
    readout=True
)

renew_limit=widgets.SelectionSlider(
    options=data['year_renew'].sort_values().unique().tolist(),
    value='1970',
    description='Data de renovo',
    continuosus_update=False,
    orientation='horizontal',
    readout=True
)

# renew_limit=widgets.Dropdown(
#     options=data['year_renew'].sort_values().unique().tolist(),
#     value   ='1971',
#     description='Data de renovo',
#     disable=False,
# )

waterfront_bar=widgets.Dropdown(
    options=data['is_waterfront'].unique().tolist(),
    value   ='no',
    description='Water View',
    disable=False,
)


def update_map(data, limit,renew,waterfront):
    data=data[(data['date']>=limit)&(data['year_renew']>=renew)&(data['is_waterfront']==waterfront)].copy()

    
    fig=plt.figure(figsize=(21,12))
    specs = gridspec.GridSpec(ncols=2, nrows=2, figure=fig)
    
    ax1=fig.add_subplot(specs[0,:]) #first rows
    ax2=fig.add_subplot(specs[1,0]) #second rows   first column
    ax3=fig.add_subplot(specs[1,1]) #second rows   second column
    
   
    
    by_date=data[['id','date']].groupby('date').sum().reset_index()
    ax1.bar (by_date['date'], by_date['id'])
      
    by_renew=data[['id','year_renew']].groupby('year_renew').sum().reset_index()
    ax2.bar (by_renew['year_renew'], by_renew['id'])
    
    by_water=data[['id','is_waterfront']].groupby('is_waterfront').sum().reset_index()
    ax3.bar (by_water['is_waterfront'], by_water['id'])    
    plt.xticks(rotation=60);

In [77]:
widgets.interactive(update_map,data=fixed(data), limit=date_limit, renew=renew_limit,waterfront=waterfront_bar)

interactive(children=(SelectionSlider(description='Disponivel para compra', index=212, options=('2014-05-02', …